replicaCount: 1

image:
  repository: bhindusuma/n01722869
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 80
  nodePort: 32111

resources: {}

autoscaling:
  enabled: false

ingress:
  enabled: false

serviceAccount:
  create: false
  name: ""
